### ISSUE TITLE
Identical style applied in one shadow dom didn't get applied it to any other identical shadow dom

### ISSUE THREAD

**Issue by zendy** [bupa-digital/shades#14]
![pasted image at 2018_07_10 11_49 am](https://user-images.githubusercontent.com/1697743/42484910-8e5d65c6-8438-11e8-816d-80ca47350b98.png)
![pasted image at 2018_07_10 11_49 am 1](https://user-images.githubusercontent.com/1697743/42484914-9478ecdc-8438-11e8-8ab6-26dbd5505a70.png)

**Comment by MiracleBlue** [comment]
This has been fixed in the latest release
