### ISSUE TITLE
Recommendation: Allow data and aria attributes to pass 

### ISSUE THREAD

**Issue by JoshRosenstein** [bupa-digital/shades#2]
https://github.com/bupa-digital/shades/blob/90625bfa0a5f085fd538c0d6bc2ab57de0c0662f/src/should-forward-prop.js#L18

|| startsWithAny('aria-', 'data-')

**Comment by MiracleBlue** [comment]
Great catch!  Thank you for that!  I've added a failing unit test that proves this behaviour and will release a patch for this in the next update (hopefully today or tomorrow).

If I could ask, for future issues, what would be greatly helpful would be an example of the incorrect behaviour in the REPL linked to in the code sandbox.  Although your keen eye caught it in the code, it's still important to us to have a tangible example.

Cheers!

**Comment by JoshRosenstein** [comment]
Will do! sorry how ive been goin about this, kinda new to coding let alone all the github norms. 
Also I extracted your main parsing logic and tweeked it a bit where it returns the calculated styled object (that way i can use and test styles across many css-js libs) and also added a few additional options, to mimic styled-systems, where it handles responsive styles and looks up values in theme prop if a key is assigned in options. Its still a work in progress, but i'll try get out a sandbox so you can visually see some of the benefits. 
 https://github.com/JoshRosenstein/styler

**Comment by JoshRosenstein** [comment]
@MiracleBlue  Sorry just read this, i am about to make a simple PR, but after that i can see what I can integrate easily, that doesnt clunk up your APIS.
