### ISSUE TITLE
Missing prefix to allow custom html attribute to pass through

### ISSUE THREAD

**Issue by wendysu** [bupa-digital/shades#20]
**Expected**
Add `html` prefix to an element custom attribute, shades will allow such attribute to pass through and translated on to actual html element on render.

**Issue**
Custom attribute are missing on end rendering result.

e.g 
`<BupaIframe htmlAllow="autoplay">`

expected output
`<iframe allow="autoplay">`

**Comment by MiracleBlue** [comment]
Fixed in v1.7.0
